### ISSUE TITLE
Endpoints Failing without ACF Pro

### ISSUE THREAD

**Issue by erwstout** [factor1/better-rest-endpoints#10]
Endpoints are broken when ACF Pro is not installed. ACF Free also fails. 

Stack trace from php7 user:

```
[19-Jan-2018 19:27:15 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function is_plugin_active() in /Users/alexanderpersky/Sites/wordpress/wp-content/plugins/better-rest-endpoints/includes/get_acf.php:12
Stack trace:
#0 /Users/alexanderpersky/Sites/wordpress/wp-content/plugins/better-rest-endpoints/includes/get_posts.php(119): bwe_get_acf()
#1 /Users/alexanderpersky/Sites/wordpress/wp-includes/rest-api/class-wp-rest-server.php(936): bwe_get_posts(Object(WP_REST_Request))
#2 /Users/alexanderpersky/Sites/wordpress/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request))
#3 /Users/alexanderpersky/Sites/wordpress/wp-includes/rest-api.php(266): WP_REST_Server->serve_request('/better-rest-en...')
#4 /Users/alexanderpersky/Sites/wordpress/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
#5 /Users/alexanderpersky/Sites/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#6 /Users/alexanderpersky/Sites/wordpress/wp-includes/plugin.php(515): WP_Hook->do_action(Array) in /Users/alexanderpersky/Sites/wordpress/wp-content/plugins/better-rest-endpoints/includes/get_acf.php on line 12
```

**Comment by bebaps** [comment]
Updated the file to 

```<?php
/**
 * Return ACF Fields
 *
 * @param none
 * @return object|null ACF object,  * or null if none.
 * @since 0.0.1
 */

function bwe_get_acf() {
  include_once( ABSPATH . 'wp-admin/includes/plugin.php' );

  // check if acf is active before doing anything
   if( is_plugin_active('advanced-custom-fields-pro/acf.php') || is_plugin_active('advanced-custom-fields/acf.php') ) {

     // get fields
     $acf_fields = get_fields();

     // if we have fields
     if( $acf_fields ) {
       return $acf_fields;
     }

   } else {
     // no acf, return false
     return false;
   }
}
```

Note the addition of `include_once( ABSPATH . 'wp-admin/includes/plugin.php' );`

So far, everything is now working that was not working before.
